### ISSUE TITLE
wrong German translation in comment header

### ISSUE THREAD

**Issue by medarob** [nitsan-technologies/ns_news_comments#21]
Hi,

I noticed that in the comment header the following english text "'Date' At 'Time'" is translated with "'Date' _Beim_ 'Time'".

Better would be "'Date' **um** 'Time' Uhr".
So instead of the current translation: "25. April 2019 Beim 13:54" it should show "25. April **um** 13:54 **Uhr**".

```
			<trans-unit id="at">
				<target>Beim</target>
			</trans-unit>
```

**Comment by nitsan-technologies** [comment]
Hey @medarob 

Thanks for noticing it.

We have done a translation from google translate and from there we got this translation.
So if you found more translation related corrections in German then please suggest us.

So that we can make it better for the users.

Cheers!

**Comment by medarob** [comment]
Thank you for your reply :)

Another thing I noticed is when I use the actual name of the month, like **July**, that the name of the month will not be translated. Is that correct or should there be a translation?

**Comment by nitsan-technologies** [comment]
Hey @medarob 

Hm, It should be translated.
But in extension, we can't detect like what user has set the date format at the backend.
There is the possibility like user may use custom date formate. 
That's why we have not set translation in that.

So, it should be managed by a developer using language translation.

Let us know if you want help in the translation in particular date formate.

Thanks :)
